Vagrant.configure(2) do |config|

    vm_memory = ENV['VM_MEMORY'] || '300'
    vm_cpus = ENV['VM_CPUS'] || '1'

    config.ssh.forward_agent = true
    config.vm.hostname = "ovnhost"
    config.vm.network "private_network", ip: "192.168.50.10"
    config.vm.box = "centos/7"
    config.vm.synced_folder './', '/vagrant', type: 'rsync'
    config.vm.synced_folder '../utils', '/vagrant/utils', type: 'rsync'

    if ENV['OVS_DIR']
        config.vm.synced_folder ENV['OVS_DIR'], '/home/vagrant/ovs', type: 'rsync'
    end

    config.vm.provider 'libvirt' do |lb|
        lb.nested = true
        lb.memory = vm_memory
        lb.cpus = vm_cpus
        lb.suspend_mode = 'managedsave'
    end

    config.vm.provision :shell do |shell|
        shell.privileged = true
        shell.path = 'install_ovn.sh'
    end

end
